# Generated by Django 5.2.7 on 2025-11-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_escalation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
