# Generated by Django 5.2.7 on 2025-11-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imageupload_options_alter_imageupload_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='negative_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escalation',
            name='positive_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escalation',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escalation',
            name='unsure_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='status',
            field=models.CharField(choices=[('unsure', 'Unsure'), ('cancer positive', 'Cancer Positive'), ('cancer negative', 'Cancer Negative')], default='pending', max_length=20),
        ),
    ]
