# Generated by Django 5.2.7 on 2025-11-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_escalation_negative_votes_escalation_positive_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalation',
            name='negative_votes',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='positive_votes',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='unsure_votes',
        ),
        migrations.AddField(
            model_name='escalation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='status',
            field=models.CharField(choices=[('unsure', 'Unsure'), ('cancer positive', 'Cancer Positive'), ('cancer negative', 'Cancer Negative')], default='unsure', max_length=20),
        ),
    ]
